swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transaction/account/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get User's Transactions
      description: API to retrieve transactions for the logged-in user
      parameters:
        - name: id
          type: number
          in: path
          description: ID of the transaction to retrieve
          required: true
        - name: month
          type: number
          in: query
          description: Month for filtering transactions
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "401":
          description: Unauthorized
        "404":
          description: Account not found
        "500":
          description: Internal Server Error
  /transaction/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get Transaction Details
      description: API to retrieve details of a specific transaction
      parameters:
        - name: id
          type: number
          in: path
          description: ID of the transaction to retrieve
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            type: object
            properties:
              id:
                type: number
                description: ID of the transaction
              transaction-type:
                type: string
                description: Type of the transaction
              category:
                type: string
                description: Category of the transaction
              note:
                type: string
                description: Note of the transaction
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update Transaction
      description: API to update category and note of a specific transaction
      parameters:
        - name: id
          type: number
          in: path
          description: ID of the transaction to update
          required: true
        - in: body
          name: body
          description: Updated category and note of the transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionReq"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/BasicRes"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: number
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transaction:
    type: object
    properties:
      # Ajoutez ici les propriétés de votre transaction
      id:
        type: number
        description: Id of the transaction
      amount:
        type: number
        description: Amount of the transaction
      balance:
        type: number
        description: Amount of the balance
      date:
        type: number
        description: Date of the transaction
      month:
        type: integer
        description: Month of the transaction
      description:
        type: string
        description: Description of the transaction
  TransactionReq:
    type: object
    properties:
      # Ajoutez ici les propriétés requises pour une requête de transaction
      category:
        type: string
      note:
        type: string
  BasicRes:
    type: object
    properties:
      message:
        type: string
